**Exercise1:**


In [2]:
import pandas as pd

In [3]:
#create the data matrix and named stat
statdata = {
    'governorate': ['Tunis', 'Tunis', 'Kairouan', 'Kairouan', 'Sfax', 'Sfax', 'Gafsa', 'Gafsa'],
    'year': [2009, 2010, 2009, 2010, 2009, 2010, 2009, 2010],
    'population': [996.4, 1000.3, 558.2, 559.7, 918.5, 931.0, 335.1, 338.1]
}
stat=pd.DataFrame(statdata)
stat

governorate  year  population
0       Tunis  2009       996.4
1       Tunis  2010      1000.3
2    Kairouan  2009       558.2
3    Kairouan  2010       559.7
4        Sfax  2009       918.5
5        Sfax  2010       931.0
6       Gafsa  2009       335.1
7       Gafsa  2010       338.1

In [4]:
#Change the order of the columns (year, governorate, population) and display the new result
stat=stat[['year', 'governorate', 'population']]
stat

year governorate  population
0  2009       Tunis       996.4
1  2010       Tunis      1000.3
2  2009    Kairouan       558.2
3  2010    Kairouan       559.7
4  2009        Sfax       918.5
5  2010        Sfax       931.0
6  2009       Gafsa       335.1
7  2010       Gafsa       338.1

In [5]:
#Create a new data matrix from stat, called stat2, by changing the row index (alphabetical number instead of numeric)
#and adding another initially empty Job variable.
#Then fill in the Employment column with the value 16.5
stat2=stat.copy()
stat2.index = [chr(i) for i in range(65, 65 + len(stat2))]
stat2['Job']=None
stat2['Employment']=16.5
stat2

year governorate  population   Job  Employment
A  2009       Tunis       996.4  None        16.5
B  2010       Tunis      1000.3  None        16.5
C  2009    Kairouan       558.2  None        16.5
D  2010    Kairouan       559.7  None        16.5
E  2009        Sfax       918.5  None        16.5
F  2010        Sfax       931.0  None        16.5
G  2009       Gafsa       335.1  None        16.5
H  2010       Gafsa       338.1  None        16.5

In [6]:
#Add another variable to stat2, named North, filled with True for the northern governorates and False otherwise.
#Then delete this variable.

northern_governorates = ['Tunis']
stat2['North'] = stat2['governorate'].isin(northern_governorates)
stat2

year governorate  population   Job  Employment  North
A  2009       Tunis       996.4  None        16.5   True
B  2010       Tunis      1000.3  None        16.5   True
C  2009    Kairouan       558.2  None        16.5  False
D  2010    Kairouan       559.7  None        16.5  False
E  2009        Sfax       918.5  None        16.5  False
F  2010        Sfax       931.0  None        16.5  False
G  2009       Gafsa       335.1  None        16.5  False
H  2010       Gafsa       338.1  None        16.5  False

In [7]:
#delete the variable 'North'
stat2 = stat2.drop(columns=['North'])
stat2

year governorate  population   Job  Employment
A  2009       Tunis       996.4  None        16.5
B  2010       Tunis      1000.3  None        16.5
C  2009    Kairouan       558.2  None        16.5
D  2010    Kairouan       559.7  None        16.5
E  2009        Sfax       918.5  None        16.5
F  2010        Sfax       931.0  None        16.5
G  2009       Gafsa       335.1  None        16.5
H  2010       Gafsa       338.1  None        16.5

**exercise 2**

In [8]:
import pandas as pd

In [11]:
data=pd.read_csv('/content/donnees_enquete_2003_television(1).txt',delimiter='\t')
data

POIDLOG        POIDSF  cLT1FREQ  cLT2FREQ  Unnamed: 4  Unnamed: 5  \
0     0.889422   4766.865201         2       1.0         NaN         NaN   
1     2.310209  12381.589746        30       1.0         NaN         NaN   
2     2.740070  14685.431344         6       2.0         NaN         NaN   
3     1.775545   9516.049939         1       1.0         NaN         NaN   
4     0.732512   3925.907588         3       1.0         NaN         NaN   
...        ...           ...       ...       ...         ...         ...   
8398  0.306852   1644.574141         6       1.0         NaN         NaN   
8399  2.501181  13405.104689         6       1.0         NaN         NaN   
8400  1.382758   7410.905653         1       1.0         NaN         NaN   
8401  0.343340   1840.132652         3       1.0         NaN         NaN   
8402  1.088486   5833.750895         0       NaN         NaN         NaN   

      Unnamed: 6  Unnamed: 7  Unnamed: 8  Unnamed: 9  ...  Unnamed: 22  \
0            NaN         NaN         NaN         NaN  ...          NaN   
1            NaN         NaN         NaN         NaN  ...          NaN   
2            NaN         NaN         NaN         NaN  ...          NaN   
3            NaN         NaN         NaN         NaN  ...          NaN   
4            NaN         NaN         NaN         NaN  ...          NaN   
...          ...         ...         ...         ...  ...          ...   
8398         NaN         NaN         NaN         NaN  ...          NaN   
8399         NaN         NaN         NaN         NaN  ...          NaN   
8400         NaN         NaN         NaN         NaN  ...          NaN   
8401         NaN         NaN         NaN         NaN  ...          NaN   
8402         NaN         NaN         NaN         NaN  ...          NaN   

      Unnamed: 23  Unnamed: 24  Unnamed: 25  Unnamed: 26  Unnamed: 27  \
0             NaN          NaN          NaN          NaN          NaN   
1             NaN          NaN          NaN          NaN          NaN   
2             NaN          NaN          NaN          NaN          NaN   
3             NaN          NaN          NaN          NaN          NaN   
4             NaN          NaN          NaN          NaN          NaN   
...           ...          ...          ...          ...          ...   
8398          NaN          NaN          NaN          NaN          NaN   
8399          NaN          NaN          NaN          NaN          NaN   
8400          NaN          NaN          NaN          NaN          NaN   
8401          NaN          NaN          NaN          NaN          NaN   
8402          NaN          NaN          NaN          NaN          NaN   

      Unnamed: 28  Unnamed: 29  Unnamed: 30  Unnamed: 31  
0             NaN          NaN          NaN          NaN  
1             NaN          NaN          NaN          NaN  
2             NaN          NaN          NaN          NaN  
3             NaN          NaN          NaN          NaN  
4             NaN          NaN          NaN          NaN  
...           ...          ...          ...          ...  
8398          NaN          NaN          NaN          NaN  
8399          NaN          NaN          NaN          NaN  
8400          NaN          NaN          NaN          NaN  
8401          NaN          NaN          NaN          NaN  
8402          NaN          NaN          NaN          NaN  

[8403 rows x 32 columns]

In [14]:
data.columns

Index(['POIDLOG', 'POIDSF', 'cLT1FREQ', 'cLT2FREQ', 'Unnamed: 4', 'Unnamed: 5',
       'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10',
       'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14',
       'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18',
       'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22',
       'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26',
       'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30',
       'Unnamed: 31'],
      dtype='object')

In [16]:
data.shape

(8403, 32)

In [27]:
#1) Remove empty columns
data=data.dropna(axis=1, how='all')
data

POIDLOG        POIDSF  cLT1FREQ  cLT2FREQ
0     0.889422   4766.865201         2       1.0
1     2.310209  12381.589746        30       1.0
2     2.740070  14685.431344         6       2.0
3     1.775545   9516.049939         1       1.0
4     0.732512   3925.907588         3       1.0
...        ...           ...       ...       ...
8398  0.306852   1644.574141         6       1.0
8399  2.501181  13405.104689         6       1.0
8400  1.382758   7410.905653         1       1.0
8401  0.343340   1840.132652         3       1.0
8402  1.088486   5833.750895         0       NaN

[8403 rows x 4 columns]

In [28]:
data.columns

Index(['POIDLOG', 'POIDSF', 'cLT1FREQ', 'cLT2FREQ'], dtype='object')

In [31]:
#2) Get the distinct values ​​for the cLT2FREQ column
data['cLT2FREQ'].unique()

array([ 1.,  2., nan,  3.])

In [40]:
#3) Modify the matrix to remove the rows for which the time unit (cLT2FREQ) is not specified or equal to zero
data = data[data['cLT2FREQ'].notna() & (data['cLT2FREQ'] != 0)]
data

POIDLOG        POIDSF  cLT1FREQ  cLT2FREQ
0     0.889422   4766.865201         2       1.0
1     2.310209  12381.589746        30       1.0
2     2.740070  14685.431344         6       2.0
3     1.775545   9516.049939         1       1.0
4     0.732512   3925.907588         3       1.0
...        ...           ...       ...       ...
8397  0.502091   2690.961176         3       1.0
8398  0.306852   1644.574141         6       1.0
8399  2.501181  13405.104689         6       1.0
8400  1.382758   7410.905653         1       1.0
8401  0.343340   1840.132652         3       1.0

[7386 rows x 4 columns]

In [41]:
data['cLT2FREQ'].unique()

array([1., 2., 3.])

In [42]:
#4) Save the result in Excel format.
data.to_excel('result.xlsx', index=False)

In [44]:
result=pd.read_excel('result.xlsx')
result

POIDLOG        POIDSF  cLT1FREQ  cLT2FREQ
0     0.889422   4766.865201         2         1
1     2.310209  12381.589746        30         1
2     2.740070  14685.431344         6         2
3     1.775545   9516.049939         1         1
4     0.732512   3925.907588         3         1
...        ...           ...       ...       ...
7381  0.502091   2690.961176         3         1
7382  0.306852   1644.574141         6         1
7383  2.501181  13405.104689         6         1
7384  1.382758   7410.905653         1         1
7385  0.343340   1840.132652         3         1

[7386 rows x 4 columns]

**Exercise 3**

In [6]:
import pandas as pd

In [10]:
dt={
   'name' :['Ali','Mohamed','Salma','Sami','Imen'],
    'Math':[9.5,15,12,16,14],
    'Info':[14,13,11,17,7],
    'Physique':[7.5,14,13,12,8.5]
}
data=pd.DataFrame(dt)
data

name  Math  Info  Physique
0      Ali   9.5    14       7.5
1  Mohamed  15.0    13      14.0
2    Salma  12.0    11      13.0
3     Sami  16.0    17      12.0
4     Imen  14.0     7       8.5

In [15]:
#1) Determine the line vector of the arithmetic averages of the grades of three subjects
averages=data[['Math','Info','Physique']].mean()
averages

Math        13.3
Info        12.4
Physique    11.0
dtype: float64

In [17]:
#2) Determine the line vector of the arithmetic ranges of the grades of three subjects
ranges=data[['Math','Info','Physique']].max() - data[["Math", "Info", "Physique"]].min()
ranges

Math         6.5
Info        10.0
Physique     6.5
dtype: float64

In [18]:
#3) Determine the line vector of the arithmetic medians of the grades of three subjects
medians=data[["Math", "Info", "Physique"]].median()
medians

Math        14.0
Info        13.0
Physique    12.0
dtype: float64

In [19]:
#4) Calculate the Y matrix of centered data and the Z matrix of centered and reduced data.
grades = data[["Math", "Info", "Physique"]]

# (Y matrix)
Y = grades - averages

# (Z matrix)
std_devs = grades.std()
Z = Y / std_devs


print("Y matrix (Centered Data):")
print(Y)

print("\nZ matrix (Centered and Reduced Data):")
print(Z)


Y matrix (Centered Data):
   Math  Info  Physique
0  -3.8   1.6      -3.5
1   1.7   0.6       3.0
2  -1.3  -1.4       2.0
3   2.7   4.6       1.0
4   0.7  -5.4      -2.5

Z matrix (Centered and Reduced Data):
       Math      Info  Physique
0 -1.468068  0.430706 -1.227881
1  0.656767  0.161515  1.052470
2 -0.502234 -0.376867  0.701646
3  1.043101  1.238278  0.350823
4  0.270434 -1.453631 -0.877058


In [22]:
#5) Calculate the RX matrix of the correlations of our data matrix and the VZ matrix of the variances and covariances of Z.
import numpy as np

RX = Z.corr()

VZ = np.cov(Z.T)

print("matrix of the correlations (RX matrix):")
print(RX)

print("\nmatrix of the variances and covariances (VZ matrix):")
print(VZ)

matrix of the correlations (RX matrix):
              Math      Info  Physique
Math      1.000000  0.140397  0.567552
Info      0.140397  1.000000  0.271510
Physique  0.567552  0.271510  1.000000

matrix of the variances and covariances (VZ matrix):
[[1.         0.14039668 0.5675521 ]
 [0.14039668 1.         0.27151049]
 [0.5675521  0.27151049 1.        ]]
